#!/usr/bin/env python3
"""
Update static gem data in content.js from gem_colors.json and
gem_colors_transfigured.json (generated by scrape_gem_colors.py).
"""
import json
import re
import sys


def load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def fmt_colors(data):
    """Build GEM_COLORS object body from gem_colors.json."""
    lines = []
    labels = {'r': 'RED (Strength)', 'g': 'GREEN (Dexterity)', 'b': 'BLUE (Intelligence)'}
    for color in ('r', 'g', 'b'):
        lines.append(f"    // ── {labels[color]} {'─' * (55 - len(labels[color]))}")
        gems = data[color]
        row = []
        for gem in gems:
            row.append(f"    '{gem}': '{color}'")
            if len(row) == 4:
                lines.append(', '.join(row) + ',')
                row = []
        if row:
            lines.append(', '.join(row) + ',')
        lines.append('')
    return '\n'.join(lines).rstrip()


def fmt_transfig(data):
    """Build TRANSFIG_GEMS object body from gem_colors_transfigured.json."""
    lines = []
    for color in ('r', 'g', 'b'):
        lines.append(f"    {color}: [")
        gems = data[color]
        row = []
        for gem in gems:
            row.append(f"'{gem}'")
            if len(row) == 3:
                lines.append('      ' + ','.join(row) + ',')
                row = []
        if row:
            lines.append('      ' + ','.join(row) + ',')
        lines.append('    ],')
    return '\n'.join(lines)


def replace_block(source, start_marker, end_marker, new_body):
    """Replace everything between start_marker and end_marker (exclusive)."""
    start = source.find(start_marker)
    end   = source.find(end_marker, start)
    if start == -1 or end == -1:
        raise ValueError(f'Could not find markers:\n  start: {start_marker!r}\n  end:   {end_marker!r}')
    return source[:start + len(start_marker)] + '\n' + new_body + '\n  ' + source[end:]


def main():
    colors     = load('gem_colors.json')
    transfig   = load('gem_colors_transfigured.json')

    with open('content.js', encoding='utf-8') as f:
        src = f.read()

    # Update GEM_COLORS
    src = replace_block(
        src,
        'const GEM_COLORS = {',
        '};',
        fmt_colors(colors),
    )

    # Update TRANSFIG_GEMS (second occurrence of '};')
    transfig_start = 'const TRANSFIG_GEMS = {'
    pos = src.find(transfig_start)
    if pos == -1:
        print('ERROR: could not find TRANSFIG_GEMS in content.js', file=sys.stderr)
        sys.exit(1)
    end = src.find('};', pos)
    src = src[:pos + len(transfig_start)] + '\n' + fmt_transfig(transfig) + '\n  ' + src[end:]

    with open('content.js', 'w', encoding='utf-8') as f:
        f.write(src)

    r = sum(len(v) for v in colors.values())
    g_count = sum(len(v) for v in transfig.values())
    print(f'GEM_COLORS updated: {r} base gems ({len(colors["r"])}r / {len(colors["g"])}g / {len(colors["b"])}b)')
    print(f'TRANSFIG_GEMS updated: {g_count} transfigured gems ({len(transfig["r"])}r / {len(transfig["g"])}g / {len(transfig["b"])}b)')


if __name__ == '__main__':
    main()
